### PR TITLE
Add option for insecure tls backend

### PR DESCRIPTION
**Pull request by VGerris**
This adds an option to be able to connect to a backend with https and self signed certificates.

### CODE REVIEW

**Comment by VGerris** [comment]
I merged additional changes in my master branch that support per route allowlists.
Now we can generate a Caddy snippet like:

```
  handle  {
    reverse_proxy @allowlist1 192.168.69.10:443 {
      transport http {
          tls_insecure_skip_verify
      }
    }
    respond @not_allowlist 404
  }

  handle /api* {
    reverse_proxy @allowlist2 192.168.69.10:443 {
      transport http {
          tls_insecure_skip_verify
      }
    }
    respond @not_allowlist1 404
  }
```
```
instead of just:
  handle  {
    reverse_proxy @allowlist 192.168.69.10:443 {
      transport http {
          tls_insecure_skip_verify
      }
    }
    respond @not_allowlist 404
  }

  handle /api* {
    reverse_proxy @allowlist 192.168.69.10:443 {
      transport http {
          tls_insecure_skip_verify
      }
    }
    respond @not_allowlist1 404
  }
```
So instead of just one allowlist for all routes, we can now set one per route.

**Comment by andyundso** [comment]
Hi @VGerris 

Sorry for the late response, I was on holidays and it seems my colleagues missed this PR.

Generally, the changes look fine. Two questions / remarks:

1. Instead of adding `tls_insecure_skip_verify` to the `Caddyfile`, would it be an option for you to just import your self-signed root certificate into the trust store of the server hosting Caddy? I would assume the certificate is then trusted on an OS-level and no changes to the role are required.
2. It would be good if we keep the support for the allowlist per site. We use this functionality internally and it would be quite a refactoring for us to adjust it to your route-based approach.

Best, Andy

**Comment by cedricwider** [comment]
Hi @VGerris,

I apologize for merging this PR before the discussion was fully resolved. I’ve reverted the changes on main to address the concerns raised, particularly around the trust store and the allowlist functionality.

We can continue the discussion here, and if needed, I can create a new PR with any additional changes that come out of it. Let me know your thoughts. Thanks again for your contribution and your patience!

**Comment by VGerris** [comment]
hi, no problem. Apologies for not catching the reply in July, I just saw someone reached put then too.
@andyundso  Do you mean that if I run say gitlab, I import those into the Caddy store?
My main goal is to keep things simple, especially because I try to automate everything with ansible and terraform mostly. To do that would require setup that allows access to both, which I prefer to avoid.

My idea with the tls_insecure_skip_verify is that the ideal implementation would work similar to a browser. 
Suppose I run gitlab.internal.mydomain.local with self signed certs. When I go there with a browser I get a warning which I can accept / store. Then it keeps working until I change the certificates : then the warning comes again, so I know it's modified and need to check if that is correct - this provides encryption with self signed certs and awareness of say man in the middle.

Ideally tls_insecure_skip_verify would work the same:
 - the first time it accepts the self signed cert and stores the signature
 - it keeps working with same signature
 - if the signature changes an error will be shown indicating a change of cert
 - the ideal user experience would be to be able to accept and store the new signature
 
Otherwise I am quite happy with how it works now personally.
So you merged and reverted I understand ?

Regarding the  tls_insecure_skip_verify, I would at it to the README. There is no need to use it, one can just import the cert I suppose.

Regarding the site option, I can imagine making some if statements to keep supporting it but that makes it less readable. If I remember correctly, just changing site to route should make it work.
To me the current way makes more sense for how I want to deploy it.
Can you think of a way to make it so we are both happy?

Would be great to keep development efforts combined!
Thank you and regards Vincent

**Comment by VGerris** [comment]
Hi, just to clarify, this PR was reverted, but was it then merged again ? thank you

**Pull request merged**
